### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by jaydorsey** [jaydorsey/env_compare#9] opened 2020-06-12 07:15 UTC
Add a changelog. Also update the gemspec to point to the right file

Look at using something like nextrelease.io, or possibly just a CHANGELOG.md in the root folder

**Comment by smridge** [comment] 2020-08-13 06:19
Closing since `CHANGELOG` was added in https://github.com/jaydorsey/env_compare/commit/6b77f234369d1613de7ce9a869883c6d97b60b48 and updated in https://github.com/jaydorsey/env_compare/commit/7bf2ac3ae07da1153585d6c23eda0eadb9aa7890 .

Confirmed gem spec points to the right file.

**Closed by smridge** 2020-08-13 06:19 UTC
